In [165]:
import networkx as nx
import random
import matplotlib.pyplot as plt
import heapq
import itertools
import numpy as np
import random
import string
import math

In [166]:
# # funkcja do tworzenia macierzy incydencji z przedziałami czasu podróży
# # zwraca połączenia pomiędzy wszystkimi wierzchołkami
# def generate_weighted_adjacency_matrix(nodes):
#     graph = np.zeros((nodes, nodes), dtype=object)
#     alphabet = list(string.ascii_uppercase)
    
#     for i in range(nodes):
#         for j in range(i+1, nodes):
#             x = random.randint(1, 8)
#             y = random.randint(x+1, 9)
#             weight = [x, y]
#             graph[i, j] = weight
#             graph[j, i] = weight
    
#     return graph

In [167]:
def generate_weighted_adjacency_matrix(nodes, total_connections):
    if total_connections > nodes * (nodes - 1) // 2:
        raise ValueError("Total connections exceed the maximum possible connections in a complete graph.")

    graph = np.zeros((nodes, nodes), dtype=object)

    # Create a list of all possible edge pairs
    all_possible_edges = [(i, j) for i in range(nodes) for j in range(i+1, nodes)]
    
    # Randomly choose edge pairs to form connections
    chosen_edges = random.sample(all_possible_edges, total_connections)
    
    for i, j in chosen_edges:
        x = random.randint(1, 8)
        y = random.randint(x + 1, 9)
        weight = [x, y]
        graph[i, j] = weight
        graph[j, i] = weight
    
    return graph


In [168]:
# przedstawienie graficzne macierzy incydencji
def display_weighted_adjacency_matrix(matrix):
    for row in matrix:
        display_row = []
        for val in row:
            if val:
                display_row.append(f"[{val[0]}, {val[1]}]")
            else:
                display_row.append("0")
        print(display_row)

In [169]:
nodes = 6
total_connections = 10  # Specify the total number of connections
graph = generate_weighted_adjacency_matrix(nodes, total_connections)
display_weighted_adjacency_matrix(graph)

['0', '0', '[6, 9]', '[1, 4]', '0', '0']
['0', '0', '[3, 6]', '[8, 9]', '[4, 7]', '[1, 4]']
['[6, 9]', '[3, 6]', '0', '[4, 7]', '0', '[5, 9]']
['[1, 4]', '[8, 9]', '[4, 7]', '0', '0', '[5, 6]']
['0', '[4, 7]', '0', '0', '0', '[7, 8]']
['0', '[1, 4]', '[5, 9]', '[5, 6]', '[7, 8]', '0']


In [170]:
def get_alphabet_letters(number):
    if number < 1 or number > 26:
        return "Invalid number"

    letters = [chr(ord('A') + i) for i in range(number)]

    return letters

In [171]:
number_of_nodes = 6

In [172]:
# graph = generate_weighted_adjacency_matrix(number_of_nodes)

In [173]:
graph_nodes = get_alphabet_letters(number_of_nodes)
graph_nodes

['A', 'B', 'C', 'D', 'E', 'F']

In [174]:
display_weighted_adjacency_matrix(graph)

['0', '0', '[6, 9]', '[1, 4]', '0', '0']
['0', '0', '[3, 6]', '[8, 9]', '[4, 7]', '[1, 4]']
['[6, 9]', '[3, 6]', '0', '[4, 7]', '0', '[5, 9]']
['[1, 4]', '[8, 9]', '[4, 7]', '0', '0', '[5, 6]']
['0', '[4, 7]', '0', '0', '0', '[7, 8]']
['0', '[1, 4]', '[5, 9]', '[5, 6]', '[7, 8]', '0']


In [175]:
graph[5,3]

[5, 6]

In [176]:
# funkcja generująca wszystkie możliwe scenariusze pomiędzy wierzchołkami dla macierzy incydencji
def generate_weight_scenarios(adjacency_matrix):
    num_vertices = len(adjacency_matrix)
    weight_scenarios = []

    for _ in range(100):
        scenario = np.zeros_like(adjacency_matrix, dtype=int)

        for i in range(num_vertices):
            for j in range(num_vertices):
                if isinstance(adjacency_matrix[i][j], list) and len(adjacency_matrix[i][j]) == 2:
                    weight_range = adjacency_matrix[i][j]
                    weight = random.randint(weight_range[0], weight_range[1])
                    scenario[i][j] = weight

        weight_scenarios.append(scenario)

    return weight_scenarios


In [177]:
scenarios = generate_weight_scenarios(graph)

In [178]:
scenarios

[array([[0, 0, 7, 2, 0, 0],
        [0, 0, 4, 8, 5, 1],
        [6, 5, 0, 6, 0, 9],
        [4, 9, 5, 0, 0, 5],
        [0, 5, 0, 0, 0, 8],
        [0, 1, 8, 5, 8, 0]]),
 array([[0, 0, 8, 2, 0, 0],
        [0, 0, 4, 9, 7, 2],
        [7, 4, 0, 5, 0, 5],
        [2, 9, 4, 0, 0, 5],
        [0, 7, 0, 0, 0, 8],
        [0, 2, 6, 5, 7, 0]]),
 array([[0, 0, 7, 3, 0, 0],
        [0, 0, 5, 8, 4, 1],
        [6, 3, 0, 5, 0, 8],
        [2, 8, 7, 0, 0, 5],
        [0, 4, 0, 0, 0, 7],
        [0, 3, 6, 6, 8, 0]]),
 array([[0, 0, 9, 4, 0, 0],
        [0, 0, 4, 8, 5, 1],
        [8, 6, 0, 7, 0, 9],
        [2, 8, 4, 0, 0, 6],
        [0, 4, 0, 0, 0, 7],
        [0, 2, 6, 6, 7, 0]]),
 array([[0, 0, 8, 1, 0, 0],
        [0, 0, 4, 9, 6, 4],
        [9, 3, 0, 6, 0, 8],
        [2, 9, 4, 0, 0, 6],
        [0, 7, 0, 0, 0, 8],
        [0, 2, 7, 5, 8, 0]]),
 array([[0, 0, 8, 2, 0, 0],
        [0, 0, 6, 9, 5, 1],
        [9, 6, 0, 7, 0, 6],
        [1, 9, 6, 0, 0, 6],
        [0, 4, 0, 0, 0, 7],
        [0

In [179]:
# def find_random_path(graph):
#     def dfs(node, path):
#         path = path + [node]
#         if len(path) == len(graph):
#             return [path]
#         paths = []
#         for neighbor, weight in enumerate(graph[node]):
#             if weight != 0 and neighbor not in path:
#                 new_paths = dfs(neighbor, path)
#                 for new_path in new_paths:
#                     paths.append(new_path)
#         return paths

#     all_paths = []
#     for node in range(len(graph)):
#         paths = dfs(node, [])
#         all_paths.extend(paths)

#     # Choose a random path from all_paths
#     random_path = random.choice(all_paths)
#     return random_path

In [198]:
def find_random_path(graph):
    def dfs(node, path):
        path = path + [node]
        if len(path) == len(graph):
            return [path]
        paths = []
        for neighbor, weight in enumerate(graph[node]):
            if weight != 0 and neighbor not in path:
                new_paths = dfs(neighbor, path)
                for new_path in new_paths:
                    paths.append(new_path)
        return paths

    all_paths = []
    for node in range(len(graph)):
        paths = dfs(node, [])
        all_paths.extend(paths)

    # Map node indices to alphabet letters
    letter_map = {i: chr(65 + i) for i in range(len(graph))}
    random_path = [letter_map[node] for node in random.choice(all_paths)]
    return random_path

In [180]:
scenarios[1]

array([[0, 0, 8, 2, 0, 0],
       [0, 0, 4, 9, 7, 2],
       [7, 4, 0, 5, 0, 5],
       [2, 9, 4, 0, 0, 5],
       [0, 7, 0, 0, 0, 8],
       [0, 2, 6, 5, 7, 0]])

In [181]:
path = find_random_path(scenarios[1])
path

[0, 2, 3, 5, 1, 4]

In [182]:
# funkcja tworząca ścieżkę losową
def generate_random_path(num_vertices):
    vertices = string.ascii_uppercase[:num_vertices]
    path_length = random.randint(4, num_vertices-2)
    path = random.sample(vertices, path_length)
    return path

In [183]:
path = generate_random_path(number_of_nodes)

In [184]:
path

['B', 'C', 'D', 'A']

In [249]:
# funkcja zwracająca wagi dla danego scenariusza
def get_path_weights(path, adjacency_matrix):
    weights = []
    exit_code = 0
    for i in range(len(path) - 1):
        start_vertex = ord(path[i]) - ord('A')
        end_vertex = ord(path[i + 1]) - ord('A')
        weight = adjacency_matrix[start_vertex][end_vertex]
        weights.append(weight)
    return weights

In [186]:
def get_random_path_with_weights(num_vertices, adjacency_matrix):
    vertices = string.ascii_uppercase[:num_vertices]
    path_length = random.randint(4, num_vertices-2)
    path = random.sample(vertices, path_length)
    weights = []
    for i in range(len(path) - 1):
        start_vertex = ord(path[i]) - ord('A')
        end_vertex = ord(path[i + 1]) - ord('A')
        weight = adjacency_matrix[start_vertex][end_vertex]
        if weight == 0:
            get_random_path_with_weights(num_vertices,adjacency_matrix)
        else:
            weights.append(weight)
    return path


In [187]:
path = get_random_path_with_weights(number_of_nodes, graph)
path

['C', 'E', 'F', 'B']

In [188]:
path_weights = get_path_weights(path, scenarios[1])
path_weights

You can't choose this path, there is no connection between 2 and 4


In [189]:
# funkcja obliczająca współczynnik żalu
def get_regret_ratio(cost, max_cost):
    regret_ratio = cost/max_cost
    return regret_ratio


In [221]:
# funkcja obliczająca współczynnik żalu dla scenariuszy
def min_max_regret_for_scenarios(path,scenarios,temperature):
    min_cost = 999
    min_regret = 999
    max_cost = 0
    min_regret_ratio = 999
    
    for i in range(len(scenarios)):
        path_weights = get_path_weights(path,scenarios[i])
        cost = sum(path_weights)
        #print(cost)
        if min_cost > cost:
            min_cost = cost
            #print("zmniejszam min cost")
            #print(min_cost)
        if max_cost < cost :
            max_cost = cost
            #print("zwiekszam max cost")
            #print(max_cost)
        regret_ratio_for_scenario = get_regret_ratio(cost, max_cost)
        delta  = regret_ratio_for_scenario - min_regret_ratio
        #print(regret_ratio_for_scenario)
        if  delta < 0 :
            min_regret_ratio = regret_ratio_for_scenario
        else:
            if math.exp(delta / temperature) > random.random():
                min_regret_ratio = regret_ratio_for_scenario
        #print("zmniejszam min_regret_ratio")
        #print(min_regret_ratio)
    return min_regret_ratio

In [191]:
best_ratio = min_max_regret_for_scenarios(path, scenarios,25)
results = {'path':[],'best_ratio':[]}

You can't choose this path, there is no connection between 2 and 4


TypeError: 'NoneType' object is not iterable

In [192]:
results['path'].append(path)
results['best_ratio'].append(best_ratio)

NameError: name 'results' is not defined

In [ ]:
print(results)

{'path': [['C', 'D', 'F', 'E']], 'best_ratio': [0.6956521739130435]}


In [213]:
# # funkcja wybierająca losowy wierzchołek w grafie, i zamieniająca go dla wierzchołka w wylosowanej ścieżce
# def change_vertex(path, graph):
#     start = path[0]
#     end = path[-1]

#     # Choose a random vertex from the path that is not the start or end vertex
#     vertex = random.choice(path[1:-1])

#     # Choose a random vertex from the remaining vertices in the graph that are not in the path and not equal 0
#     new_vertex = random.choice([v for v in graph if v not in path and v != 0])

#     # Replace the selected vertex with the new vertex
#     index = path.index(vertex)
#     path[index] = new_vertex

#     return path

In [242]:
class NoSuitableVerticesException(Exception):
    pass

In [276]:
def change_vertex(path, graph, results):
    start = path[0]
    end = path[-1]

    # Choose a random vertex from the path that is not the start or end vertex
    vertex = random.choice(path[1:-1])
    # Convert the alphabet letters back to indices
    vertex_index = ord(vertex) - ord('A')

    # Find vertices that are not in the path and have a weight not equal to 0
    suitable_vertices = [chr(ord('A') + v) for v in range(len(graph)) if chr(ord('A') + v) not in path and graph[vertex_index][v] != 0]


    if suitable_vertices:
        # Choose a random vertex from suitable_vertices
        new_vertex = random.choice(suitable_vertices)

        # Replace the selected vertex with the new vertex
        index = path.index(vertex)
        path[index] = new_vertex

        return path
    else:
        # If there are no suitable vertices, return get_min_ratio_path(results)
        result = get_min_ratio_path(results)
        raise NoSuitableVerticesException(f"No suitable vertices found, result is {result}")


In [194]:
# funkcja zwracająca scieżkę z najmniejszym współczynnikiem żalu
def get_min_ratio_path(data):
    paths = data['path']
    ratios = data['best_ratio']

    min_ratio_index = ratios.index(min(ratios))
    min_ratio = ratios[min_ratio_index]
    min_ratio_path = paths[min_ratio_index]

    return min_ratio, min_ratio_path

In [195]:
change_vertex(path, graph_nodes)

['C', 'E', 'D', 'B']

In [245]:
# proces symulowanego wyrzażania
def simulated_annealing(number_of_nodes, total_connections, number_of_iterations, initial_temperature, cooling_coefficient):
    results = {'path': [], 'best_ratio': []}
    graph = generate_weighted_adjacency_matrix(number_of_nodes, total_connections)
    graph_nodes = get_alphabet_letters(number_of_nodes)
    display_weighted_adjacency_matrix(graph)
    scenarios = generate_weight_scenarios(graph)
    test_scenario = scenarios[1]
    path = find_random_path(test_scenario)
    print(path)
    try:
        for iteration in range(number_of_iterations):
            temperature = initial_temperature / (1 + iteration * cooling_coefficient)
            best_ratio = min_max_regret_for_scenarios(path, scenarios, temperature)
            results['path'].append(path)
            results['best_ratio'].append(best_ratio)
            path = change_vertex(path, test_scenario, results)
    except NoSuitableVerticesException:
        return get_min_ratio_path(results)

    return get_min_ratio_path(results)


In [301]:
simulated_annealing(8,20,5,100,0.85)

['0', '[4, 6]', '0', '[6, 8]', '0', '0', '[8, 9]', '0']
['[4, 6]', '0', '[6, 8]', '[2, 6]', '[8, 9]', '0', '[1, 5]', '[7, 8]']
['0', '[6, 8]', '0', '[5, 7]', '[1, 5]', '[1, 8]', '0', '0']
['[6, 8]', '[2, 6]', '[5, 7]', '0', '[5, 7]', '0', '[8, 9]', '[7, 8]']
['0', '[8, 9]', '[1, 5]', '[5, 7]', '0', '[7, 9]', '[5, 6]', '[6, 7]']
['0', '0', '[1, 8]', '0', '[7, 9]', '0', '[7, 8]', '[6, 7]']
['[8, 9]', '[1, 5]', '0', '[8, 9]', '[5, 6]', '[7, 8]', '0', '[8, 9]']
['0', '[7, 8]', '0', '[7, 8]', '[6, 7]', '[6, 7]', '[8, 9]', '0']
['A', 'G', 'D', 'B', 'C', 'E', 'F', 'H']


(0.9803921568627451, ['A', 'G', 'D', 'B', 'C', 'E', 'F', 'H'])